# Changes here will be overwritten by Copier
_commit: 0.4.0
_src_path: https://github.com/fastapi-mvc/copier-generator
copyright_date: 2022
generator: generator
generator_name: generator
github_actions: true
license: MIT
nix: true
repo_url: https://github.com/fastapi-mvc/copier-generator
